// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6nc-At3gpPfQA6rKhCm-Yww6ObZTjR1k',
    appId: '1:45050320623:web:26ef09a81e1c8bc0dd6d1a',
    messagingSenderId: '45050320623',
    projectId: 'shop-with-friend',
    authDomain: 'shop-with-friend.firebaseapp.com',
    storageBucket: 'shop-with-friend.firebasestorage.app',
    measurementId: 'G-6K252GFEWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsrlGVZ7NZmJ-FZwrAxdOlTEbAwWsMqE',
    appId: '1:45050320623:android:11d8a2516d5b5669dd6d1a',
    messagingSenderId: '45050320623',
    projectId: 'shop-with-friend',
    storageBucket: 'shop-with-friend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzTSepV7jfSoDcv4ZgVMP-AZOXYBgyhw',
    appId: '1:45050320623:ios:7d897a5f83642dffdd6d1a',
    messagingSenderId: '45050320623',
    projectId: 'shop-with-friend',
    storageBucket: 'shop-with-friend.firebasestorage.app',
    iosBundleId: 'com.example.sippylifeAssesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFzTSepV7jfSoDcv4ZgVMP-AZOXYBgyhw',
    appId: '1:45050320623:ios:7d897a5f83642dffdd6d1a',
    messagingSenderId: '45050320623',
    projectId: 'shop-with-friend',
    storageBucket: 'shop-with-friend.firebasestorage.app',
    iosBundleId: 'com.example.sippylifeAssesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6nc-At3gpPfQA6rKhCm-Yww6ObZTjR1k',
    appId: '1:45050320623:web:69f7c496c20c693fdd6d1a',
    messagingSenderId: '45050320623',
    projectId: 'shop-with-friend',
    authDomain: 'shop-with-friend.firebaseapp.com',
    storageBucket: 'shop-with-friend.firebasestorage.app',
    measurementId: 'G-7VN1NS202L',
  );
}
